- name: Auto-scaling our instances
  local_action:
    module: ec2_asg
    name: bastien-auto-scaling
    region: "{{aws_region}}"
    launch_config_name: bastien-scaling-config
    load_balancers: bastien-load-balancer
    health_check_period: 300
    health_check_type: EC2
    min_size: 2
    max_size: 12
    desired_capacity: 2