- name: Creating our load-balancer
  local_action:
    module: ec2_elb_lb
    name: bastien-load-balancer
    region: "{{aws_region}}"
    scheme: internet-facing    
    security_group_ids: "{{ ec2_security_group.group_id }}"
    state: present
    subnets:
      - subnet-d9bd4f80
      - subnet-3f0e1c17
      - subnet-e9e183d3
      - subnet-19c2126e
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80