- name: Attaching our instances to it
  local_action:
    module: ec2_elb
    instance_id: "{{ item.id }}"
    region: "{{ aws_region }}"
    ec2_elbs: "bastien-load-balancer"
    state: 'present'
  with_items: ec2.instances