- name: Spawning our EC2 instances
  hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
  - include: tasks/aws/ec2_create_security_group.yml
  - include: tasks/aws/ec2_launch_instances.yml
  - include: tasks/aws/ec2_add_instances_to_host_group.yml
  - include: tasks/aws/ec2_tag_instances.yml
  - include: tasks/aws/ec2_wait_for_instances.yml

- name: Preparing our instances
  hosts: aws-ec2
  sudo: True
  gather_facts: True
  tasks:
  - include: tasks/ubuntu/update_system.yml
  - include: tasks/apache2/apache2.yml
  - name: Wait for Apache to listen to ::80
    wait_for: port=80 delay=60 timeout=90 state=started

- name: Preparing our infrastructure
  hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:    
  - include: tasks/aws/ec2_load-balancing.yml
  - include: tasks/aws/ec2_auto-scaling.yml
  - include: tasks/aws/ec2_create_scaling_policies.yml
  - include: tasks/aws/ec2_create_scaling_alarms.yml